# This a config file for triagebot

[range-diff]

[review-changes-since]

[mentions."#[rustc_attr]"]
type = "content"
cc = ["@Urgau"]

[mentions."*.txt"]
message = "valid glob"

[shortcut]

[relabel]

[assign]

[review-submitted]
# These labels are removed when a review is submitted.
review_labels = ["S-waiting-on-review"]
# This label is added when a review is submitted.
reviewed_label = "S-waiting-on-author"
