# This a config file for triagebot

[range-diff]

[review-changes-since]

[mentions."#[rustc_attr]"]
type = "content"
cc = ["@Urgau"]

[mentions."a.txt"]
cc = ["Urgau"]

[shortcut]

[relabel]

[assign]

[assign.owners]
"*" = ["@Urgau"]

[assign.adhoc_groups]
fallback = ["@Urgau"]

[assign.check_activity]
warning_after = 6
release_assignment_after = 7

#[assign.community_reviews]
#minimum_reviews = 1
#label = "S-waiting-on-community-reviews"

[review-submitted]
# These labels are removed when a review is submitted.
review_labels = ["S-waiting-on-review"]
# This label is added when a review is submitted.
reviewed_label = "S-waiting-on-author"

#[view-all-comments-link]
#threashold = 5

[merge-conflicts]

#[merge]
#type = "merge-queue"

[lock]
